-- banksms v2 — the rebuilt schema. Five tables. See FalconGo/docs/BANKSMS_REBUILD_PROPOSAL.md.
--
-- This file is BOTH the fresh-install migration (run by sqlx::migrate! on an
-- empty database, e.g. integration tests) AND the DDL the `apex-rust cutover`
-- subcommand executes inside its one big transaction on production. The cutover
-- stamps this version into a fresh banksms._sqlx_migrations afterwards, so the
-- migrator sees it as already applied. Keep every statement schema-qualified:
-- the migrator connection's search_path is banksms-first, but the cutover's is
-- not.

CREATE SCHEMA IF NOT EXISTS banksms;

-- ---------------------------------------------------------------------------
-- raw_messages: every message from the chat, verbatim, forever.
-- status is the PARSER'S verdict only — recomputable, never human-owned.
-- Human action lives in transactions (a manual row linked by raw_message_id).
-- ---------------------------------------------------------------------------
CREATE TABLE banksms.raw_messages (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wa_message_id TEXT NOT NULL UNIQUE,          -- the dedup key. Non-negotiable.
  chat_jid      TEXT NOT NULL,
  sender        TEXT,
  is_from_me    BOOLEAN NOT NULL DEFAULT FALSE,
  wa_timestamp  TIMESTAMPTZ NOT NULL,           -- envelope time, UTC
  body          TEXT NOT NULL,                  -- original, never normalized
  media_type    TEXT,
  status        TEXT NOT NULL CHECK (status IN ('matched','ignored','suppressed')),
  template      TEXT,                           -- which template matched (matched/suppressed)
  ingested_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX raw_messages_status_ts_idx ON banksms.raw_messages (status, wa_timestamp DESC);

-- ---------------------------------------------------------------------------
-- transactions: one user-owned column set. The parser writes it once at
-- creation; edits update in place and stamp edited_by/edited_at. No parsed_*
-- twins, no overrides ledger — the verbatim body is one join away and the
-- parser is deterministic.
-- ---------------------------------------------------------------------------
CREATE TABLE banksms.transactions (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source           TEXT NOT NULL CHECK (source IN ('whatsapp','import','manual')),
  raw_message_id   BIGINT UNIQUE REFERENCES banksms.raw_messages(id),
  import_source_id BIGINT UNIQUE,               -- legacy fleet_expenses.id
  direction        TEXT NOT NULL CHECK (direction IN ('in','out')),
  amount           NUMERIC(18,4) NOT NULL CHECK (amount > 0),
  currency         TEXT NOT NULL DEFAULT 'EGP',
  occurred_at      TIMESTAMPTZ NOT NULL,
  account          TEXT,
  counterparty     TEXT,
  reference        TEXT,
  category         TEXT,
  description      TEXT,
  payment_method   TEXT,
  company          TEXT,
  car_id           BIGINT REFERENCES public.cars(id),
  car_no_plate     TEXT,
  driver_id        BIGINT REFERENCES public.drivers(id),
  employee_id      BIGINT REFERENCES public.employees(id),
  -- The public.loans row this transaction registered (advance/loan/salary).
  -- Replaces the old transaction_postings link table: the link is strictly 1:1.
  -- Invariant: apex-rust only ever touches loans rows recorded here.
  loan_id          BIGINT UNIQUE,
  paid_by          TEXT,                        -- legacy import free text; new rows use party ids
  version          INTEGER NOT NULL DEFAULT 1,  -- If-Match optimistic concurrency
  created_by       TEXT,
  edited_by        TEXT,
  edited_at        TIMESTAMPTZ,
  deleted_at       TIMESTAMPTZ,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT whatsapp_has_raw CHECK (source <> 'whatsapp' OR raw_message_id IS NOT NULL),
  CONSTRAINT import_has_id    CHECK ((source = 'import') = (import_source_id IS NOT NULL)),
  CONSTRAINT single_party     CHECK (driver_id IS NULL OR employee_id IS NULL)
);
CREATE INDEX transactions_occurred_idx ON banksms.transactions (occurred_at DESC, id DESC)
  WHERE deleted_at IS NULL;
CREATE INDEX transactions_category_idx ON banksms.transactions (category)
  WHERE deleted_at IS NULL;

-- ---------------------------------------------------------------------------
-- parse_templates: the regexes, in POST-normalization form, named capture
-- groups. `sample` is a real message the pattern must match — validated on
-- every write and re-asserted at boot, so a broken pattern fails loudly
-- instead of silently draining messages into 'ignored'.
-- ---------------------------------------------------------------------------
CREATE TABLE banksms.parse_templates (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          TEXT NOT NULL UNIQUE,
  pattern       TEXT NOT NULL,
  date_formats  JSONB NOT NULL,                 -- ordered chrono format list, per template
  direction_map JSONB NOT NULL DEFAULT '{}',
  sample        TEXT NOT NULL,
  priority      INTEGER NOT NULL,
  enabled       BOOLEAN NOT NULL DEFAULT TRUE,
  notes         TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- categories: labels plus the two columns that drive the money flow.
-- posting_kind non-NULL means "categorising into this registers a loans row of
-- that kind". required_party is independent — production's Salary category
-- requires a person but posts nothing.
-- ---------------------------------------------------------------------------
CREATE TABLE banksms.categories (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key            TEXT NOT NULL UNIQUE,
  label          TEXT NOT NULL,
  label_ar       TEXT NOT NULL,
  posting_kind   TEXT CHECK (posting_kind IN ('advance','loan','salary')),
  required_party TEXT NOT NULL DEFAULT 'none'
                 CHECK (required_party IN ('none','driver','employee','either')),
  sort_order     INTEGER NOT NULL DEFAULT 100,
  enabled        BOOLEAN NOT NULL DEFAULT TRUE
);

-- ---------------------------------------------------------------------------
-- ingest_cursor: singleton composite cursor. Advanced once per poll cycle,
-- after every page has committed, monotonically. Never per page.
-- ---------------------------------------------------------------------------
CREATE TABLE banksms.ingest_cursor (
  id                 INTEGER PRIMARY KEY CHECK (id = 1),
  chat_jid           TEXT NOT NULL,
  last_wa_timestamp  TIMESTAMPTZ,
  last_wa_message_id TEXT,
  last_poll_at       TIMESTAMPTZ,
  last_error         TEXT,
  last_error_at      TIMESTAMPTZ,
  consecutive_errors INTEGER NOT NULL DEFAULT 0,
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ===========================================================================
-- Seeds: the six production-validated templates plus the two variants that
-- close the last coverage gap (100/100 against the full corpus, verified by
-- execution 2026-08-12). Patterns are post-normalization; samples are raw.
-- ===========================================================================

INSERT INTO banksms.parse_templates (name, pattern, date_formats, direction_map, sample, priority, notes) VALUES
('arabic_ipn',
 $rx$تم\s+(?P<action_ar>خصم|اضافه|ايداع)\s+مبلغ\s+(?P<currency>[A-Z]{3})\s+(?P<amount>[\d,]+\.\d{2})\s+من\s+حساب\s+\**(?P<account>\d{3,6})\b.*?بتاريخ\s+(?P<date>\d{2}-\d{2}-\d{4})\s+(?P<time>\d{2}:\d{2})\s+الي\s+(?P<counterparty>.+?)\s+برقم\s+مرجعي\s+(?P<reference>[A-Z0-9]+)$rx$,
 '["%d-%m-%Y"]', '{"خصم":"out","اضافه":"in","ايداع":"in"}',
 'يرجى العلم أنه تم خصم مبلغ EGP 8800.00 من حساب ********9276 عبر شبكة المدفوعات اللحظية (IPN) من خلال خدمات الإنترنت البنكية بتاريخ 12-08-2026 19:52 إلى AHMED A........ A... برقم مرجعي FT26225STJBS للمزيد، يرجي الاتصال بـ 19666.',
 10, 'Hotline 19666. Reference FT + alphanumeric. Counterparty partially masked.'),

('instant_purchase',
 $rx$تم\s+تنفيذ\s+عمليه\s+شراء\s+(?P<action_ar>لحظي)\s+من\s+حسابك\s+المنتهي\s+ب\s*\**(?P<account>\d{3,6})\s+بمبلغ\s+(?P<amount>[\d,]+\.\d{2})\s+(?P<currency>جم|ج\.م|[A-Z]{3})\s+من\s+(?P<counterparty>.+?)\s+برقم\s+مرجعي\s+(?P<reference>[A-Za-z0-9]+)\s+بتاريخ\s+(?P<date>\d{2}-\d{2}-\d{4})\s+(?P<time>\d{2}:\d{2})(?:.*?الرصيد\s+المتاح\s+(?:[A-Z]{3}\s+)?(?P<balance>[\d,]+\.\d{2}))?$rx$,
 '["%d-%m-%Y"]', '{"لحظي":"out"}',
 'يرجى العلم انه تم تنفيذ عملية شراء لحظي من حسابك المنتهي بـ ********5447 بمبلغ 135.72 جم من Mobile Recharge برقم مرجعي cdec344b بتاريخ 10-08-2026 12:15 الرصيد المتاح 85635.98 جم للمزيد، برجاء الاتصال بـ 19666. ',
 13, 'Hotline 19666. Instant PURCHASE variant: merchant after من, optional balance.'),

('instant_transfer_in',
 $rx$تم\s+تنفيذ\s+تحويل\s+(?P<action_ar>لحظي)\s+بمبلغ\s+(?P<amount>[\d,]+\.\d{2})\s+(?P<currency>جم|ج\.م|[A-Z]{3})\s+الي\s+حسابك\s+المنتهي\s+ب\s*\**(?P<account>\d{3,6})\s+من\s+(?P<counterparty>.+?)\s+برقم\s+مرجعي\s+(?P<reference>[A-Za-z0-9]+)\s+بتاريخ\s+(?P<date>\d{2}-\d{2}-\d{4})\s+(?P<time>\d{2}:\d{2})$rx$,
 '["%d-%m-%Y"]', '{"لحظي":"in"}',
 'يرجى العلم انه تم تنفيذ تحويل لحظي بمبلغ 5700.00 جم إلى حسابك المنتهي بـ ********5447 من احمد عبدالتواب سيد احمد برقم مرجعي 6c28c740 بتاريخ 11-08-2026 10:43 للمزيد، برجاء الاتصال بـ 19666',
 14, 'Hotline 19666. INBOUND instant transfer: الي حسابك ... من <sender>. A credit.'),

('instant_transfer',
 $rx$تم\s+تنفيذ\s+تحويل\s+(?P<action_ar>لحظي)\s+بمبلغ\s+(?P<amount>[\d,]+\.\d{2})\s+(?P<currency>جم|ج\.م|[A-Z]{3})\s+من\s+حسابك\s+المنتهي\s+ب\s*\**(?P<account>\d{3,6})\b.*?برقم\s+مرجعي\s+(?P<reference>[A-Za-z0-9]+)\s+بتاريخ\s+(?P<date>\d{2}-\d{2}-\d{4})\s+(?P<time>\d{2}:\d{2})$rx$,
 '["%d-%m-%Y"]', '{"لحظي":"out"}',
 'يرجى العلم انه تم تنفيذ تحويل لحظي بمبلغ 1000.00 جم من حسابك المنتهي بـ ********5447 برقم مرجعي d31e85e3 بتاريخ 12-08-2026 20:53 للمزيد، برجاء الاتصال بـ 19666 ',
 15, 'Hotline 19666. Outbound, currency written جم, no counterparty, bare hex reference.'),

('wallet_transfer',
 $rx$تم\s+تنفيذ\s+تحويل\s+(?P<action_ar>لحظي)\s+من\s+حسابكم\s+رقم\s+\**(?P<account>\d{3,6})\s+بمبلغ\s+(?P<amount>[\d,]+\.\d{2})\s+(?P<currency>جم|ج\.م|[A-Z]{3})\s+الي\s+(?P<counterparty>.+?)\s+رقم\s+مرجعي\s+(?P<reference>[A-Za-z0-9]+)\s+يوم\s+(?P<date>\d{2}-\d{2})\s+الساعه\s+(?P<time>\d{1,2}:\d{2})$rx$,
 '["%m-%d"]', '{"لحظي":"out"}',
 'تم تنفيذ تحويل لحظي من حسابكم رقم 0180 بمبلغ 70000.00 جم إلى petroapp c** رقم مرجعي 552921316865 يوم 08-10 الساعة 10:50 للمزيد اتصل بـ 19623',
 16, 'Hotline 19623. Year-less MONTH-FIRST date (%m-%d), verified against live arrivals. Usually PetroApp → suppressed.'),

('cib_card',
 $rx$تم\s+(?P<action_ar>سحب|خصم)\s+مبلغ\s+(?P<currency>[A-Z]{3})\s+(?P<amount>[\d,]+\.\d{2})\s+من\s+بطاقه\s+الخصم\s+المباشر\s+المنتهيه\s+ب\s+\**(?P<account>\d{4})\s+من\s+(?P<counterparty>.+?)\s+في\s+(?P<date>\d{1,2}/\d{1,2}/\d{2})\s+(?P<time>\d{1,2}:\d{2})\s*،\s*الرصيد\s+المتاح\s+(?:[A-Z]{3}\s+)?(?P<balance>[\d,]+\.\d{2})$rx$,
 '["%d/%m/%y"]', '{"خصم":"out","سحب":"out"}',
 'تم سحب مبلغ  EGP 8000.00  من بطاقة الخصم المباشر المنتهية بـ **2234 من CIB EL NASRBR 2 BNA في 08/08/26 10:32 ، الرصيد المتاح EGP 8579.76',
 20, 'CIB debit-card withdrawal. No reference number exists in this format; counterparty is a branch/merchant.'),

('abk',
 $rx$Your\s+(?P<bank>[\w\-]+)\s+account\s+\*(?P<account>\d{3,6})\s+was\s+(?P<action>credited|debited)\s+with\s+(?P<currency>[A-Z]{3})\s+(?P<amount>[\d,]+(?:\.\d+)?)\s+on\s+(?P<date>\d{1,2}/\d{1,2}/\d{2,4})\s+(?P<time>\d{1,2}:\d{2})\s+(?:with|for)\s+IPN\s+transfer\s+(?P<preposition>from|to)\s+(?P<counterparty>.+?)\s*\(ID\s+(?P<reference>\w+)\)$rx$,
 '["%m/%d/%y","%m/%d/%Y"]', '{"debited":"out","credited":"in"}',
 'Your ABK-Egypt account *7647 was debited with EGP 30.5 on 8/8/26 19:08 for IPN transfer to سامى نصحى رزق الله خليل (ID 6e234130).For queries call 19322',
 30, 'Hotline 19322. MONTH-FIRST dates — the only such template. Amounts may have 1-2 decimals.'),

('ref_balance',
 $rx$Transfer\s+reference\s+#(?P<reference>\w+)\s+of\s+(?P<currency>[A-Z]{3})\s+(?P<amount>[\d,]+\.\d{2})\s+has\s+been\s+(?P<action>debited|credited)\s+from\s+your\s+account\s+(?P<account>[\d\-]+)\s+through\s+IPN\s+on\s+(?P<date>\d{2}/\d{2}/\d{4})\s+at\s+(?P<time>\d{2}:\d{2}),\s*your\s+available\s+balance\s+is\s+(?P<balance>[\d,]+\.\d{2})$rx$,
 '["%d/%m/%Y"]', '{"debited":"out","credited":"in"}',
 'Transfer reference #4b19beef of EGP 2000.00 has been debited from your account 6001-01 through IPN on 09/08/2026 at 08:16, your available balance is 953.48. For inquiries, call 19555.',
 40, 'Hotline 19555. Balance drift is how fee-exclusive amounts are detectable.');

INSERT INTO banksms.categories (key, label, label_ar, posting_kind, required_party, sort_order) VALUES
('Advance',       'Advance',        'سلفة',           'advance', 'either', 10),
('Loan',          'Loan',           'قرض',            'loan',    'either', 11),
('SalaryPortion', 'Part of salary', 'جزء من الراتب',  'salary',  'either', 12),
('Salary',        'Salary payment', 'راتب',           NULL,      'either', 20),
('Fuel',          'Fuel',           'وقود',           NULL,      'none',   30),
('Labor',         'Labor',          'عمالة',          NULL,      'none',   40),
('Parts',         'Parts',          'قطع غيار',       NULL,      'none',   50),
('Maintenance',   'Maintenance',    'صيانة',          NULL,      'none',   60),
('Repairs',       'Repairs',        'إصلاحات',        NULL,      'none',   70),
('Insurance',     'Insurance',      'تأمين',          NULL,      'none',   80),
('Registration',  'Registration',   'ترخيص',          NULL,      'none',   90),
('Other',         'Other',          'أخرى',           NULL,      'none',   999);
